version: '3.8'
services:
  db:
    container_name: pg_url
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urldb
  url:
    container_name: url-shortener
    image: gs/url-shortener:latest
    restart: always
    environment:
      QUARKUS_DATASOURCE_USERNAME: username
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://pg_url:5432/urldb
    ports:
      - "8080:8080"
    depends_on:
      - db